/*
 * Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com) All Rights Reserved.
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package io.ballerina.lib.wso2.icp.compiler;

import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Holds the OpenAPI documents generated by {@link SwaggerPackCollectTask} keyed by the resource
 * path they should be written to, for {@link SwaggerPackLifecycleTask} to embed into the JAR
 * once it has been built. A single instance is created per compilation in
 * {@link SwaggerPackCompilerPlugin#init} and shared between the two tasks; wrapping the backing
 * map in a dedicated type (rather than passing a raw {@code Map} around) keeps that intentional
 * shared, mutable state from tripping "exposes internal representation" static analysis checks.
 */
final class OpenApiDocumentStore {

    private final Map<String, byte[]> documents = new ConcurrentHashMap<>();

    void put(String resourcePath, byte[] content) {
        documents.put(resourcePath, content);
    }

    boolean isEmpty() {
        return documents.isEmpty();
    }

    Set<Map.Entry<String, byte[]>> entries() {
        return documents.entrySet();
    }
}
