[package]
org = "wso2"
name = "artifacts_tests"
version = "1.0.1"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../../native/build/libs/icp.runtime.bridge-native-1.0.1.jar"

[build-options]
remoteManagement=true
