[package]
org = "wso2"
name = "artifacts_tests"
version = "0.2.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../../native/build/libs/icp.runtime.bridge-native-0.2.0.jar"

[build-options]
remoteManagement=true
